package com.pkh.schedule.mapper;

import com.pkh.schedule.po.SysScheduler;
import com.pkh.schedule.po.SysSchedulerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysSchedulerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int countByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int deleteByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int insert(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int insertSelective(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    List<SysScheduler> selectByExample(SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    SysScheduler selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysScheduler record, @Param("example") SysSchedulerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysScheduler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysScheduler record);
}