package com.pkh.schedule.po;

import java.util.Date;

public class SysScheduler {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.cron
     *
     * @mbggenerated
     */
    private String cron;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.job_trigger
     *
     * @mbggenerated
     */
    private String jobTrigger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.service_function
     *
     * @mbggenerated
     */
    private String serviceFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.schedule_description
     *
     * @mbggenerated
     */
    private String scheduleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_scheduler.is_execute
     *
     * @mbggenerated
     */
    private String isExecute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.id
     *
     * @return the value of sys_scheduler.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.id
     *
     * @param id the value for sys_scheduler.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.cron
     *
     * @return the value of sys_scheduler.cron
     *
     * @mbggenerated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.cron
     *
     * @param cron the value for sys_scheduler.cron
     *
     * @mbggenerated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.job_trigger
     *
     * @return the value of sys_scheduler.job_trigger
     *
     * @mbggenerated
     */
    public String getJobTrigger() {
        return jobTrigger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.job_trigger
     *
     * @param jobTrigger the value for sys_scheduler.job_trigger
     *
     * @mbggenerated
     */
    public void setJobTrigger(String jobTrigger) {
        this.jobTrigger = jobTrigger == null ? null : jobTrigger.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.service_function
     *
     * @return the value of sys_scheduler.service_function
     *
     * @mbggenerated
     */
    public String getServiceFunction() {
        return serviceFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.service_function
     *
     * @param serviceFunction the value for sys_scheduler.service_function
     *
     * @mbggenerated
     */
    public void setServiceFunction(String serviceFunction) {
        this.serviceFunction = serviceFunction == null ? null : serviceFunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.modify_time
     *
     * @return the value of sys_scheduler.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.modify_time
     *
     * @param modifyTime the value for sys_scheduler.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.schedule_description
     *
     * @return the value of sys_scheduler.schedule_description
     *
     * @mbggenerated
     */
    public String getScheduleDescription() {
        return scheduleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.schedule_description
     *
     * @param scheduleDescription the value for sys_scheduler.schedule_description
     *
     * @mbggenerated
     */
    public void setScheduleDescription(String scheduleDescription) {
        this.scheduleDescription = scheduleDescription == null ? null : scheduleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_scheduler.is_execute
     *
     * @return the value of sys_scheduler.is_execute
     *
     * @mbggenerated
     */
    public String getIsExecute() {
        return isExecute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_scheduler.is_execute
     *
     * @param isExecute the value for sys_scheduler.is_execute
     *
     * @mbggenerated
     */
    public void setIsExecute(String isExecute) {
        this.isExecute = isExecute == null ? null : isExecute.trim();
    }
}