package com.pkh.schedule.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysSchedulerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public SysSchedulerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCronIsNull() {
            addCriterion("cron is null");
            return (Criteria) this;
        }

        public Criteria andCronIsNotNull() {
            addCriterion("cron is not null");
            return (Criteria) this;
        }

        public Criteria andCronEqualTo(String value) {
            addCriterion("cron =", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotEqualTo(String value) {
            addCriterion("cron <>", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronGreaterThan(String value) {
            addCriterion("cron >", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronGreaterThanOrEqualTo(String value) {
            addCriterion("cron >=", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLessThan(String value) {
            addCriterion("cron <", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLessThanOrEqualTo(String value) {
            addCriterion("cron <=", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronLike(String value) {
            addCriterion("cron like", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotLike(String value) {
            addCriterion("cron not like", value, "cron");
            return (Criteria) this;
        }

        public Criteria andCronIn(List<String> values) {
            addCriterion("cron in", values, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotIn(List<String> values) {
            addCriterion("cron not in", values, "cron");
            return (Criteria) this;
        }

        public Criteria andCronBetween(String value1, String value2) {
            addCriterion("cron between", value1, value2, "cron");
            return (Criteria) this;
        }

        public Criteria andCronNotBetween(String value1, String value2) {
            addCriterion("cron not between", value1, value2, "cron");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIsNull() {
            addCriterion("job_trigger is null");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIsNotNull() {
            addCriterion("job_trigger is not null");
            return (Criteria) this;
        }

        public Criteria andJobTriggerEqualTo(String value) {
            addCriterion("job_trigger =", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotEqualTo(String value) {
            addCriterion("job_trigger <>", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerGreaterThan(String value) {
            addCriterion("job_trigger >", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerGreaterThanOrEqualTo(String value) {
            addCriterion("job_trigger >=", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLessThan(String value) {
            addCriterion("job_trigger <", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLessThanOrEqualTo(String value) {
            addCriterion("job_trigger <=", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerLike(String value) {
            addCriterion("job_trigger like", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotLike(String value) {
            addCriterion("job_trigger not like", value, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerIn(List<String> values) {
            addCriterion("job_trigger in", values, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotIn(List<String> values) {
            addCriterion("job_trigger not in", values, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerBetween(String value1, String value2) {
            addCriterion("job_trigger between", value1, value2, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andJobTriggerNotBetween(String value1, String value2) {
            addCriterion("job_trigger not between", value1, value2, "jobTrigger");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionIsNull() {
            addCriterion("service_function is null");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionIsNotNull() {
            addCriterion("service_function is not null");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionEqualTo(String value) {
            addCriterion("service_function =", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionNotEqualTo(String value) {
            addCriterion("service_function <>", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionGreaterThan(String value) {
            addCriterion("service_function >", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionGreaterThanOrEqualTo(String value) {
            addCriterion("service_function >=", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionLessThan(String value) {
            addCriterion("service_function <", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionLessThanOrEqualTo(String value) {
            addCriterion("service_function <=", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionLike(String value) {
            addCriterion("service_function like", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionNotLike(String value) {
            addCriterion("service_function not like", value, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionIn(List<String> values) {
            addCriterion("service_function in", values, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionNotIn(List<String> values) {
            addCriterion("service_function not in", values, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionBetween(String value1, String value2) {
            addCriterion("service_function between", value1, value2, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andServiceFunctionNotBetween(String value1, String value2) {
            addCriterion("service_function not between", value1, value2, "serviceFunction");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionIsNull() {
            addCriterion("schedule_description is null");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionIsNotNull() {
            addCriterion("schedule_description is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionEqualTo(String value) {
            addCriterion("schedule_description =", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionNotEqualTo(String value) {
            addCriterion("schedule_description <>", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionGreaterThan(String value) {
            addCriterion("schedule_description >", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("schedule_description >=", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionLessThan(String value) {
            addCriterion("schedule_description <", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("schedule_description <=", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionLike(String value) {
            addCriterion("schedule_description like", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionNotLike(String value) {
            addCriterion("schedule_description not like", value, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionIn(List<String> values) {
            addCriterion("schedule_description in", values, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionNotIn(List<String> values) {
            addCriterion("schedule_description not in", values, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionBetween(String value1, String value2) {
            addCriterion("schedule_description between", value1, value2, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andScheduleDescriptionNotBetween(String value1, String value2) {
            addCriterion("schedule_description not between", value1, value2, "scheduleDescription");
            return (Criteria) this;
        }

        public Criteria andIsExecuteIsNull() {
            addCriterion("is_execute is null");
            return (Criteria) this;
        }

        public Criteria andIsExecuteIsNotNull() {
            addCriterion("is_execute is not null");
            return (Criteria) this;
        }

        public Criteria andIsExecuteEqualTo(String value) {
            addCriterion("is_execute =", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteNotEqualTo(String value) {
            addCriterion("is_execute <>", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteGreaterThan(String value) {
            addCriterion("is_execute >", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteGreaterThanOrEqualTo(String value) {
            addCriterion("is_execute >=", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteLessThan(String value) {
            addCriterion("is_execute <", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteLessThanOrEqualTo(String value) {
            addCriterion("is_execute <=", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteLike(String value) {
            addCriterion("is_execute like", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteNotLike(String value) {
            addCriterion("is_execute not like", value, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteIn(List<String> values) {
            addCriterion("is_execute in", values, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteNotIn(List<String> values) {
            addCriterion("is_execute not in", values, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteBetween(String value1, String value2) {
            addCriterion("is_execute between", value1, value2, "isExecute");
            return (Criteria) this;
        }

        public Criteria andIsExecuteNotBetween(String value1, String value2) {
            addCriterion("is_execute not between", value1, value2, "isExecute");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_scheduler
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_scheduler
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}